icons_format = "{icon}"

[theme]
theme = "plain"

[icons]
icons = "material-nf"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:30) |"
short = " $title.str(max_w:30) |"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:0.5) $play $next |}"
interface_name_exclude = [".*kdeconnect.*", "mpd"]

[[block]]
block = "taskwarrior"
interval = 60
format = " $icon count.eng(w:1) tasks "
format_singular = " $icon 1 task "
format_everything_done = " $icon 0 task "
warning_threshold = 10
critical_threshold = 20
[[block.filters]]
name = "today"
filter = "+PENDING +OVERDUE or +DUETODAY"
[[block.filters]]
name = "all"
filter = "+PENDING"

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "available"
# alert_unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# format = " $icon root: $available.eng(w:2) "
#
# [[block]]
# block = "memory"
# format = " $icon $mem_used_percents.eng(w:2) "
# format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
#
# [[block]]
# block = "cpu"
# interval = 1
# format = " $icon $barchart $utilization "
# format_alt = " $icon $frequency{ $boost|} "
# info_cpu = 20
# warning_cpu = 50
# critical_cpu = 90

[[block]]
block = "docker"
interval = 2
format = " $icon $running/$total "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "hueshift"
hue_shifter = "gammastep"
step = 50
click_temp = 3500

[[block]]
block = "battery"
format = " $percentage {$time |}"
device = "DisplayDevice"
full_format = " FULL "
driver = "upower"

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%a %d/%m/%y %R') "

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
[block.mappings]
"English (US)" = "US"
"Turkish (N/A)" = "TR"
